export type { Result, Failure } from './Result'
export { SuccessResult, FailureResult } from './Result'

export { arraysEqual } from './arraysEqual'
export { backwardCompose } from './backwardCompose'
export { createCustomReducer } from './createCustomReducer'
export { preventDefaultPropagation } from './preventDefaultPropagation'
export { getNewJobColor } from './getNewJobColor'
export { msToFormattedTime } from './msToFormattedTime'
export { formattedTimeToMs } from './formattedTimeToMs'
export { shallowEqualObjects } from './shallowEqualObjects'