name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        REACT_APP_API_URL: "https://job-shop-collection-api.azurewebsites.net"
        REACT_APP_HOST: "azure"
    steps:            
    - name: Checkout the repo
      uses: actions/checkout@v1

    - name: Install npm packages
      run: npm install

    - name: Test app
      run: npm run test

    - name: Build app
      run: npm run build
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .build-app
        path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:            
    - name: Login to Azure
      id: login_azure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .build-app

    - name: Set Azure subscription
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az account set -s ${{ secrets.AZURE_SUBSCRIPTION }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name jobshopcollectionblob -s . -d '$web'

    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "jobshopcollection" --name "jobshopcollection" --resource-group "JobShopCollectionResourceGroup"

    - name: Logout of Azure
      if: ${{ always() && steps.login_azure.outcome == 'success' }}
      continue-on-error: true
      run: az logout
